2024-12-24 10:26:08,183 | INFO | "test_challenge" выполнен успешно
2024-12-24 10:26:08,183 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-12-24 10:26:08,183 | WARNING | Traceback (most recent call last):
  File "C:\StudyProjects\pythonProject1\tests_12_4.py", line 83, in test_run
    runner = Runner(2)
  File "C:\StudyProjects\pythonProject1\tests_12_4.py", line 17, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-12-24 10:26:08,183 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-12-24 10:26:08,183 | WARNING | Traceback (most recent call last):
  File "C:\StudyProjects\pythonProject1\tests_12_4.py", line 72, in test_walk
    runner = Runner("Вася", -5)
  File "C:\StudyProjects\pythonProject1\tests_12_4.py", line 22, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

